<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

# Linear Algebra - Part 1

In [1]:
import numpy as np

### 1. Compute the scaler product of two vectors

In mathematics, the dot product or scalar product is an algebraic operation that takes two equal-length sequences of numbers (usually coordinate vectors) and returns a single number. 

We can calculate it this way:

        a · b = ax × bx + ay × by
        
Hint: [Dot Product](https://www.mathsisfun.com/algebra/vectors-dot-product.html)

```
# Expected Output:
0
```

In [2]:
a = [-12, 16]
b = [12, 9]

In [3]:
np.dot(a,b)

0

### 2. Compute the cross product of two vectors

> When a and b start at the origin point (0,0,0), the Cross Product will end at:

        cx = aybz − azby
        cy = azbx − axbz
        cz = axby − aybx
        
Hint: [Cross Product](https://www.mathsisfun.com/algebra/vectors-cross-product.html)
```
# Expected Output:
array([[-3,  6, -3],
       [ 3, -6,  3]])
```

In [4]:
x = np.array([[1,2,3], [4,5,6]])
y = np.array([[4,5,6], [1,2,3]])

In [5]:
np.cross(x,y)

array([[-3,  6, -3],
       [ 3, -6,  3]])

### 3. Compute the Hademard product (entry-wise multiplication) of two vectors.

> In mathematics, the Hadamard product (also known as the Schur product[1] or the entrywise product[2]:ch. 5) is a binary operation that takes two matrices of the same dimensions and produces another matrix of the same dimension as the operands where each element i, j is the product of elements i, j of the original two matrices. It should not be confused with the more common matrix product. It is attributed to, and named after, either French mathematician Jacques Hadamard or German mathematician Issai Schur. [Wiki](https://en.wikipedia.org/wiki/Hadamard_product_(matrices))

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/4eb9bb54b2820fb3583901ec05bc4b474b6d90bc)
```
# Expected Output:
array([[ 5, 12],
       [21, 32]])
```

In [6]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [7]:
print(np.multiply(a,b))

[[ 5 12]
 [21 32]]


### 4. Compute the sum of two matrices.

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/0fb7845af355c550d44020e52699069c044126a9)
```
# Expected Output:
[17, 15, 4]
[10, 12, 9]
[11, 13, 18]
```

In [8]:
# Program to add two matrices using nested loop

X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[5,8,1],
    [6,7,3],
    [4,5,9]]

result = [[0,0,0],
         [0,0,0],
         [0,0,0]]

In [9]:
for index in range(len(X)):
    for index2 in range(3):
        result[index][index2] = X[index][index2] + Y[index][index2]
for r in result:
    print(r)

    

[17, 15, 4]
[10, 12, 9]
[11, 13, 18]


In [10]:
# Additional! Which gives the same result as above without writing a loop

np.add(X,Y)

array([[17, 15,  4],
       [10, 12,  9],
       [11, 13, 18]])

### 5. Compute the product of two matrices.

![](https://upload.wikimedia.org/wikipedia/commons/e/eb/Matrix_multiplication_diagram_2.svg)
```
# Expected Output:
[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]
```

In [11]:
# Program to multiply two matrices using nested loops

# 3x3 matrix
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

# 3x4 matrix
Y = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]

# result is 3x4
result = [[0,0,0,0],
         [0,0,0,0],
         [0,0,0,0]]

In [12]:
#Additional! Without writing a loop, it gives the same result as above
np.dot(X,Y)

array([[114, 160,  60,  27],
       [ 74,  97,  73,  14],
       [119, 157, 112,  23]])

In [13]:
# i is row index for X matrix
for i in range(len(X)):
    
    # j is row index for Y matrix
    for j in range(len(Y[0])):
        
        # k is row index for Y matrix
        for k in range(len(Y)):
        
            result[i][j] += X[i][k] * Y[k][j]
        
for r in result:
    print(r)


[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


In [14]:
##### STEPS OF CALCULATING THE MATRIX #####

#Step 1                                  #Step 13                                    #Step 25
i = 0                                    i = 1                                       i = 2
j = 0                                    j = 0                                       j = 0
k = 0                                    k = 0                                       k = 0

12 * 5 = 60                              4 * 5 = 20                                  7 * 5 = 35

#Step 2                                  #Step 14                                    #Step 26
i = 0                                    i = 1                                       i = 2
j = 0                                    j = 0                                       j = 0
k = 1                                    k = 1                                       k = 1

7 * 6 = 42                               5 * 6 = 30                                  8 * 6 = 48                                

#Step 3                                  #Step 15                                    #Step 27
i = 0                                    i = 1                                       i = 2
j = 0                                    j = 0                                       j = 0
k = 2                                    k = 2                                       k = 2

3 * 4 = 12                               6 * 4 = 24                                  9 * 4 = 36

60 + 42 + 12 = 114                       20 + 30 + 24 = 74                           35 + 48 + 36 = 119

#Step 4                                  #Step 16                                    #Step 28
i = 0                                    i = 1                                       i = 2
j = 1                                    j = 1                                       j = 1
k = 0                                    k = 0                                       k = 0

12 * 8 = 96                              4 * 8 = 32                                  7 * 8 = 56

#Step 5                                  #Step 17                                    #Step 29
i = 0                                    i = 1                                       i = 2 
j = 1                                    j = 1                                       j = 1
k = 1                                    k = 1                                       k = 1
                                      
7 * 7 = 49                               5 * 7 = 35                                  8 * 7 = 56

#Step 6                                  #Step 18                                    #Step 30
i = 0                                    i = 1                                       i = 2
j = 1                                    j = 1                                       j = 1
k = 2                                    k = 2                                       k = 2

3 * 5 = 15                               6 * 5 = 30                                  9 * 5 = 45

96 + 49 + 15 = 160                       32 + 35 + 30 = 97                           56 + 56 + 45 = 157

#Step 7                                  #Step 19                                    #Step 31
i = 0                                    i = 1                                       i = 2
j = 2                                    j = 2                                       j = 2
k = 0                                    k = 0                                       k = 0

12 * 1 = 12                              4 * 1 = 4                                   7 * 1 = 7

#Step 8                                  #Step 20                                    #Step 32
i = 0                                    i = 1                                       i = 2
j = 2                                    j = 2                                       j = 2
k = 1                                    k = 1                                       k = 1

7 * 3 = 21                               5 * 3 = 15                                  8 * 3 = 24

#Step 9                                  #Step 21                                    #Step 33
i = 0                                    i = 1                                       i = 2
j = 2                                    j = 2                                       j = 2
k = 2                                    k = 2                                       k = 2

3 * 9 = 27                               6 * 9 = 54                                  9 * 9 = 81

12 + 21 + 27 = 60                        4 + 15 + 54 = 73                            7 + 24 + 81 = 112

#Step 10                                 #Step 22                                    #Step 34
i = 0                                    i = 1                                       i = 2
j = 3                                    j = 3                                       j = 3
k = 0                                    k = 0                                       k = 0

12 * 2 = 24                              4 * 2 = 8                                   7 * 2 = 14

#Step 11                                 #Step 23                                    #Step 35
i = 0                                    i = 1                                       i = 2
j = 3                                    j = 3                                       j = 3
k = 1                                    k = 1                                       k = 1

7 * 0 = 0                                5 * 0 = 0                                   8 * 0 = 0

#Step 12                                 #Step 24                                    #Step 36
i = 0                                    i = 1                                       i = 2
j = 3                                    j = 3                                       j = 3
k = 2                                    k = 2                                       k = 2

3 * 1 = 3                                6 * 1 = 6                                   9 * 1 = 9

24 + 0 + 3 = 27                          8 + 0 + 6 = 14                              14 + 0 + 9 = 23

    





SyntaxError: invalid syntax (Temp/ipykernel_19812/2143913695.py, line 4)

### 6. Compute the determinant of an n x n matrix.

![](https://integratedmlai.com/wp-content/uploads/2018/12/Matrix_Det_2x2.png)

Hint: [Find the Determinant of a Matrix with Pure Python without Numpy or Scipy](https://integratedmlai.com/find-the-determinant-of-a-matrix-with-pure-python-without-numpy-or-scipy/)

Hint: Use 
> np.linalg.det
```
# Expected Output:
17.999999999999996
```

In [15]:
matrix = [[-2,2,-3],[-1,1,3],[2,0,-1]]

In [16]:
np.linalg.det(matrix)

17.999999999999996

### 7. Compute the inverse of an n x n matrix.

For a 3×3 matrix

![](http://mathworld.wolfram.com/images/equations/MatrixInverse/NumberedEquation3.gif)

the matrix inverse is

![](http://mathworld.wolfram.com/images/equations/MatrixInverse/NumberedEquation4.gif)

Hint: Use 
> from numpy.linalg import inv
```
# Expected Output:
array([[-2. ,  1. ],
       [ 1.5, -0.5]])
```

In [17]:
a = np.array([[1., 2.], [3., 4.]])

In [18]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])



---



---



> > > > > > > > > © 2021 Institute of Data


---



---



